[ES-14111] Fix null ref to element
locus-taxy/react-popover pull request #2
Opened 2020-02-10 09:16 UTC by RithikaChowta

Fixes #210

[ES-14111](https://locussh.atlassian.net/browse/ES-14111)

2020-02-10 17:31 UTC, nikhil892 requested changes
We should also commit the yarn.lock file to maintain version locks throughout

2020-02-10 18:12 UTC, nikhil892 commented
Also let's test this well to ensure that things don't break..

2020-02-11 06:18 UTC, RithikaChowta commented
> We should also commit the yarn.lock file to maintain version locks throughout

There were no changes in the dependencies of `react-popover`.. Hence no diff in yarn.lock. The current lock file is already present in master

2020-02-12 04:37 UTC, nikhil892 approved these changes

2020-02-12 08:32 UTC, merged